// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3Bucket) DeepCopyInto(out *AwsS3Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3Bucket.
func (in *AwsS3Bucket) DeepCopy() *AwsS3Bucket {
	if in == nil {
		return nil
	}
	out := new(AwsS3Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsS3Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketApplyServerSideEncryptionByDefault) DeepCopyInto(out *AwsS3BucketApplyServerSideEncryptionByDefault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketApplyServerSideEncryptionByDefault.
func (in *AwsS3BucketApplyServerSideEncryptionByDefault) DeepCopy() *AwsS3BucketApplyServerSideEncryptionByDefault {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketApplyServerSideEncryptionByDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketCorsRule) DeepCopyInto(out *AwsS3BucketCorsRule) {
	*out = *in
	if in.AllowedMethods != nil {
		in, out := &in.AllowedMethods, &out.AllowedMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExposeHeaders != nil {
		in, out := &in.ExposeHeaders, &out.ExposeHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketCorsRule.
func (in *AwsS3BucketCorsRule) DeepCopy() *AwsS3BucketCorsRule {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketCorsRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketDestination) DeepCopyInto(out *AwsS3BucketDestination) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketDestination.
func (in *AwsS3BucketDestination) DeepCopy() *AwsS3BucketDestination {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketExpiration) DeepCopyInto(out *AwsS3BucketExpiration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketExpiration.
func (in *AwsS3BucketExpiration) DeepCopy() *AwsS3BucketExpiration {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketLifecycleRule) DeepCopyInto(out *AwsS3BucketLifecycleRule) {
	*out = *in
	out.Expiration = in.Expiration
	out.NoncurrentVersionExpiration = in.NoncurrentVersionExpiration
	out.Transition = in.Transition
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.NoncurrentVersionTransition = in.NoncurrentVersionTransition
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketLifecycleRule.
func (in *AwsS3BucketLifecycleRule) DeepCopy() *AwsS3BucketLifecycleRule {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketLifecycleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketList) DeepCopyInto(out *AwsS3BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AwsS3Bucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketList.
func (in *AwsS3BucketList) DeepCopy() *AwsS3BucketList {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsS3BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketLogging) DeepCopyInto(out *AwsS3BucketLogging) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketLogging.
func (in *AwsS3BucketLogging) DeepCopy() *AwsS3BucketLogging {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketNoncurrentVersionExpiration) DeepCopyInto(out *AwsS3BucketNoncurrentVersionExpiration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketNoncurrentVersionExpiration.
func (in *AwsS3BucketNoncurrentVersionExpiration) DeepCopy() *AwsS3BucketNoncurrentVersionExpiration {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketNoncurrentVersionExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketNoncurrentVersionTransition) DeepCopyInto(out *AwsS3BucketNoncurrentVersionTransition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketNoncurrentVersionTransition.
func (in *AwsS3BucketNoncurrentVersionTransition) DeepCopy() *AwsS3BucketNoncurrentVersionTransition {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketNoncurrentVersionTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketReplicationConfiguration) DeepCopyInto(out *AwsS3BucketReplicationConfiguration) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketReplicationConfiguration.
func (in *AwsS3BucketReplicationConfiguration) DeepCopy() *AwsS3BucketReplicationConfiguration {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketReplicationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketRule) DeepCopyInto(out *AwsS3BucketRule) {
	*out = *in
	if in.ApplyServerSideEncryptionByDefault != nil {
		in, out := &in.ApplyServerSideEncryptionByDefault, &out.ApplyServerSideEncryptionByDefault
		*out = make([]AwsS3BucketApplyServerSideEncryptionByDefault, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketRule.
func (in *AwsS3BucketRule) DeepCopy() *AwsS3BucketRule {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketRules) DeepCopyInto(out *AwsS3BucketRules) {
	*out = *in
	out.Destination = in.Destination
	out.SourceSelectionCriteria = in.SourceSelectionCriteria
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketRules.
func (in *AwsS3BucketRules) DeepCopy() *AwsS3BucketRules {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketServerSideEncryptionConfiguration) DeepCopyInto(out *AwsS3BucketServerSideEncryptionConfiguration) {
	*out = *in
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = make([]AwsS3BucketRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketServerSideEncryptionConfiguration.
func (in *AwsS3BucketServerSideEncryptionConfiguration) DeepCopy() *AwsS3BucketServerSideEncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketServerSideEncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketSourceSelectionCriteria) DeepCopyInto(out *AwsS3BucketSourceSelectionCriteria) {
	*out = *in
	out.SseKmsEncryptedObjects = in.SseKmsEncryptedObjects
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketSourceSelectionCriteria.
func (in *AwsS3BucketSourceSelectionCriteria) DeepCopy() *AwsS3BucketSourceSelectionCriteria {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketSourceSelectionCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketSpec) DeepCopyInto(out *AwsS3BucketSpec) {
	*out = *in
	if in.LifecycleRule != nil {
		in, out := &in.LifecycleRule, &out.LifecycleRule
		*out = make([]AwsS3BucketLifecycleRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Website != nil {
		in, out := &in.Website, &out.Website
		*out = make([]AwsS3BucketWebsite, len(*in))
		copy(*out, *in)
	}
	out.Logging = in.Logging
	if in.ReplicationConfiguration != nil {
		in, out := &in.ReplicationConfiguration, &out.ReplicationConfiguration
		*out = make([]AwsS3BucketReplicationConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.CorsRule != nil {
		in, out := &in.CorsRule, &out.CorsRule
		*out = make([]AwsS3BucketCorsRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServerSideEncryptionConfiguration != nil {
		in, out := &in.ServerSideEncryptionConfiguration, &out.ServerSideEncryptionConfiguration
		*out = make([]AwsS3BucketServerSideEncryptionConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketSpec.
func (in *AwsS3BucketSpec) DeepCopy() *AwsS3BucketSpec {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketSseKmsEncryptedObjects) DeepCopyInto(out *AwsS3BucketSseKmsEncryptedObjects) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketSseKmsEncryptedObjects.
func (in *AwsS3BucketSseKmsEncryptedObjects) DeepCopy() *AwsS3BucketSseKmsEncryptedObjects {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketSseKmsEncryptedObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketTransition) DeepCopyInto(out *AwsS3BucketTransition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketTransition.
func (in *AwsS3BucketTransition) DeepCopy() *AwsS3BucketTransition {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketVersioning) DeepCopyInto(out *AwsS3BucketVersioning) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketVersioning.
func (in *AwsS3BucketVersioning) DeepCopy() *AwsS3BucketVersioning {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketVersioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsS3BucketWebsite) DeepCopyInto(out *AwsS3BucketWebsite) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsS3BucketWebsite.
func (in *AwsS3BucketWebsite) DeepCopy() *AwsS3BucketWebsite {
	if in == nil {
		return nil
	}
	out := new(AwsS3BucketWebsite)
	in.DeepCopyInto(out)
	return out
}
