apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backends.terraform.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status
    description: Description of the current status
    name: Status
    type: string
  group: terraform.io
  names:
    kind: Backend
    listKind: BackendList
    plural: backends
    singular: backend
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            endpoints:
              description: EtcdV3 backend endpoints
              items:
                type: string
              type: array
            lock:
              description: EtcdV3 backend lock
              type: boolean
            prefix:
              description: EtcdV3 backend prefix
              type: string
          type: object
        status:
          type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
