apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform.fullname" . }}
  labels:
    app: {{ include "terraform.name" . }}
    chart: {{ include "terraform.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "terraform.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "terraform.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /srv/manager
        args:
        - --enable-leader-election
        imagePullPolicy: Always
        volumeMounts:
        - name: admission-secrets
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9440
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 30
          periodSeconds: 15
      serviceAccountName: terraform-operator
      volumes:
      - name: admission-secrets
        secret:
          secretName: terraform-operator-admission
