apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "terraform.fullname" . }}
  labels:
    app: {{ include "terraform.name" . }}
    chart: {{ include "terraform.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "terraform.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "terraform.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - terraform-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "terraform-operator"
            - name: TFPATH
              value: "/tmp"
          volumeMounts:
            - mountPath: {{ .Values.etcdDir }}
              name: etcd-certs
      serviceAccountName: terraform-operator
      volumes:
        - name: etcd-certs
          hostPath:
            path: {{ .Values.etcdDir }}
