kind: ServiceAccount
apiVersion: v1
metadata:
  name: terraform-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-terraform-operator
subjects:
- kind: ServiceAccount
  name: terraform-operator
roleRef:
  kind: Role
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
