kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
rules:
- apiGroups:
  - awss3buckets.terraform.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - awss3buckets
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-terraform-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
