{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
{{- if .Values.serviceAccount.gcpServiceAccount.create }}
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccount.gcpServiceAccount.name }}"
{{- end }}
metadata:
  name: {{ .Values.serviceAccount.name }}
{{- end }}
