---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  labels:
    chart: prometheus-operator
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.21.*
spec:
  releaseName: metrics
  chart:
    git: ssh://git@github.com/krubot/terraform-operator
    ref: master
    path: charts/prometheus-operator
  values:
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      adminPassword: admin
