apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-operator-admission-create
  namespace: infra
spec:
  template:
    metadata:
      name: terraform-operator-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=terraform-operator-webhook,terraform-operator-webhook.infra.svc
        - --namespace=infra
        - --secret-name=terraform-operator-admission
        image: jettech/kube-webhook-certgen:v1.0.0
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      serviceAccount: terraform-operator-admission
